from os import getenv
from mode_switch import mode_setup

mode_setup()

ANNOUNCEMENTS_CHANNEL = int(getenv("ANNOUNCEMENTS_CHANNEL"))
SUBMISSIONS_CHANNEL = int(getenv("SUBMISSIONS_CHANNEL"))
VOTED_CHANNEL = int(getenv("VOTED_CHANNEL"))
TALK_TO_THE_STAFF_CHANNEL = int(getenv("TALK_TO_THE_STAFF_CHANNEL"))

LISTENERS_ROLE_MENTION = "<@&" + str(getenv("LISTENERS_ROLE")) + ">"

SUBMISSIONS_OPEN_DAY = "Sunday"
SUBMISSIONS_OPEN_HOUR = 0
SUBMISSIONS_OPEN_MINUTE = 0
SUBMISSIONS_CLOSED_DAY = "Thursday"
SUBMISSIONS_CLOSED_HOUR = 0
SUBMISSIONS_CLOSED_MINUTE = 0
